### ISSUE TITLE
Compatibility AA

### ISSUE THREAD

**Issue by Tenneteu** [Rusketh/FML_Calculator#3]
It breaks the "Hide" Button in Area Actions Preview Mode.
My guess is that the hidden calculator window still overlays the AA Hide Button, making a click unable to reach.

**Comment by Rusketh** [comment]
Hi,
Sorry about the late reply. I unfortunately do not and probably never will use area actions (it is an amazing mod though).
I have made some changes to the way the new calculator handles focus. Could you please re-test this bug and advise.
If the bug is still present are you able to provide more information on how the game and use of Area Actions is effected since I am unfamiliar with the usage of AA.

Thank you

**Comment by Rusketh** [comment]
Had a friend who uses AA test for this bug tonight using calculator v0.0.4 and was unable to reproduce the bug.
I will hence close this issue.
